### ISSUE TITLE
RC_01 Identificación de Usuarios

### ISSUE THREAD

**Issue by ldcb** [ldcb/MALAA#1]
- [ ] AU_01 Agregar Usuario.
- [ ] AU_02 Activa Usuario.
- [ ] AU_03 Inicio de Sesión Usuario (Login). 
- [ ] AU_04 Pantalla de Usuario o Usuario Admin
