### ISSUE TITLE
RC_02 Administrar Productos del Catálogo.

### ISSUE THREAD

**Issue by ldcb** [ldcb/MALAA#2]
- [ ] AP_01 Agregar Producto.
- [ ] AP_02 Eliminar Producto.
- [ ] AP_03 Editar Producto.
