### ISSUE TITLE
RC_03 Carrito de Compras

### ISSUE THREAD

**Issue by ldcb** [ldcb/MALAA#3]
- [ ] CC_01 Añadir Producto.
- [ ] CC_02 Eliminar Producto.
- [ ] CC_03 Ver compra.
- [ ] CC_04 Finalizar Compra.
