### ISSUE TITLE
RC_05 Configuración de Usuario

### ISSUE THREAD

**Issue by ldcb** [ldcb/MALAA#5]
- [ ] CU_01 Dato Generales.
- [ ] CU_02 Métodos de Pago.
- [ ] CU_03 Direcciones de Entrega.
